### ISSUE TITLE
Editor Loosing Its Measure in Certain Scenario

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#942] opened 2021-11-25 05:14 UTC
We started seeing this problem recently when an editor seems to lost its measure and displaying as blank editor - this fix/updates when the window resizes:

![image](https://user-images.githubusercontent.com/24370870/143382998-45e22aff-2499-4bec-8b6b-49fe28515483.png)

I found the following steps to reproduce this every time:

1. Open any project
2. Open any two files to editors, i.e. file-A, file-B
3. Open `Moonshine > Settings > Default SDK`
4. Change the default SDK to something else and save the settings
5. LS tries to update itself in status bar
6. Once LS update completes, click on the editor tab between file-A or file-B that is not selected
7. Newly selected tab showing editor lost its measure [Bug]

**Comment by piotrzarzycki21** [comment] 2021-11-26 16:12
Quite annoying issue. Quite often all my opened tabs (apart from active) are going blank and I have to close them and reopen.

**Comment by JoelProminic** [comment] 2021-11-29 18:34
I can also reproduce it like this:

1. Close all projects
2. Restart Moonshine
3. Create/open a Java Gradle project
4. Open build.gradle
5. Create/open a Java Maven project
6. Open pom.xml
7. Select build.gradle tab
8. Moonshine > Settings
9. Click Cancel.  BUG:  the pom.xml editor is selected instead.  The position of the tabs changes as well. 
10. Repeat steps 8 and 9.  BUG:  build.gradle editor is selected, but the tab does not render

I didn't see the language server update in this case, so I don't think that is the central problem.

I confirmed this can also trigger with the New Project dialog.  I think I have also seen it when opening and closing other files, but I can't reproduce this currently.

@piotrzarzycki21, resizing the window causes the editor to render again, so you don't have to reopen the tabs.

**Comment by joshtynjala** [comment] 2021-11-30 19:09
There are no exceptions thrown when this happens?

**Comment by piotrzarzycki21** [comment] 2021-11-30 19:26
> There are no exceptions thrown when this happens?

Unfortunately not. Console do not show up anything.

**Comment by joshtynjala** [comment] 2021-12-08 19:00
I have not been able to reproduce this issue. I tried following the steps, from both @rat-moonshine and @JoelProminic, but I'm not seeing the issue trigger on my machine. Is this still happening for anyone?

**Comment by JoelProminic** [comment] 2021-12-08 23:29
I tried the latest nightly build (2266), and my test procedure doesn't trigger any more.  I see that in step 9, the pom.xml tab has focus, but the positions of the tabs does not change.

I could not reproduce @rat-moonshine's procedure either.  Note that you need to clear the custom SDK for a Flex project before you can trigger a language server restart by changing the Default SDK.

The blank editor window has triggered for me with the Dev build recently, but I didn't pay attention to the sequence at the time.   I'll look for another reproduceable test procedure if I find this again.

**Comment by JoelProminic** [comment] 2021-12-08 23:51
@piotrzarzycki21 suggested that this triggered when we open enough tabs that they can't be displayed at once.  This seems to be the trick:
1. Close all tabs and projects and restart MoonshineDevelopment
2. Open a project
3. Open enough files so that there are hidden tabs
4. Close the current tab.  Note that the second-to-last tab is selected, and a previously hidden tab is shown at the end.
5. Select the other tab - it is not displayed properly.

https://user-images.githubusercontent.com/24532731/145309068-2073e883-193e-46ae-b67b-ec04de6a036d.mov

I confirmed that my test procedure will still trigger if I am using Moonshine with the original window dimensions.  In this case, the Settings window in step 8 causes a tab to be hidden, so it seems like the hidden tabs are probably the underlying cause here.

**Comment by joshtynjala** [comment] 2021-12-09 17:35
Thanks, I can now reproduce!

**Closed** 2021-12-09 18:15 UTC
Labels: bug, HaxeMigration, Editor

**Comment by JoelProminic** [comment] 2021-12-09 20:32
I couldn't reproduce the problem after your update.   We can reopen the issue if we find another case that triggers this behavior.
