### ISSUE TITLE
Occasional File Sorting Problem in Sidebar After File System Watcher Events

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#1029] opened 2022-05-16 04:59 UTC
From @JustinProminic 

> After moving around several source files using Mac Finder after having do a "Show In Finder" right click operation, the change watcher mechanism resulted in folders showing in Moonshine without being sorted alphabetically.
> 
> Here is a screen shot:
> 
> ![image](https://user-images.githubusercontent.com/24370870/168522648-22332878-e518-44ef-9c74-3ccae5ece819.png)

**Comment by rat-moonshine** [comment] 2022-05-16 05:09
A quick look into the codes I found that [tree.refresh(..)](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/plugin/project/ProjectPlugin.as#L392) method calls against both the events from `FSWatcherPlugin` - `WatchedFileChangeEvent.FILE_CREATED`, `WatchedFileChangeEvent.FILE_DELETED`. 

Inside `Tree.refresh(..)` we already has sort-children calls [added](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/components/views/project/TreeView.mxml#L214) if pre-conditions are met. However, the existing [pre-condition](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/components/views/project/TreeView.mxml#L204) may not be valid in case of new file and when its `FileWrapper` still not exists to the collection. 

Even if we wants to sort-children irrespective of pre-conditions, we still needs the _parent_ where we wants to sort. Currently, the _parent_ calculates based on the `FileWrapper` object returns by the pre-condition. 

I need to give this a though. @joshtynjala welcome to make changes if something came up to him before me.

**Comment by rat-moonshine** [comment] 2022-06-16 10:35
I spent a long time on trying to understand when this occurs. Even at times when I see this happening, reproducing this became terribly difficult, thus a debug. 

We can keep adding `sortChildren(..)` here and there but that is not a good way to fix this, and this will also increase memory stress unnecessarily. 

In trying to shorten our search area, I'm temporarily disabling `FSWatcherPlugin` and suggest some tests of the build. This change is currently limited to macOS branch build of Moonshine. @JoelProminic please give tests to the build for some time. If the problem continue to be seen in the build, at least it'll ensure it's not from `FSWatcherPlugin` updates.

**Comment by joshtynjala** [comment] 2022-07-07 17:58
I found a way to consistently reproduce the file sorting issue. At least on my machine.

1. Build the **MoonshineDESKTOPevolved** project inside Moonshine.
2. Open _bin-debug/elements/as3mxml-language-server_ in the tree.
3. Build **MoonshineDESKTOPevolved** again.
4. Files in _elements_ and _as3mxml-language-server_ are not in the correct order.

I determined that the `refreshItem()` method in _TreeView.mxml_ would not only refresh a directory's `FileWrapper` children, but also the children of any open sub-directories (recursively). However, in `refresh()` we were calling `sortChildren()` for the parent directory only. The open sub-directories remained unsorted after they were refreshed. My fix was simply to call `sortChildren()` for each of the open sub-directories too.

Please give it a try and report back if you still see occasional sorting issues.

**Comment by piotrzarzycki21** [comment] 2022-07-08 10:53
After last update when I do clean project I'm getting following error:

```
: Error #1009
: TypeError: Error #1009
: 	at components.views.project::TreeView/refresh()
: 	at actionScripts.plugin.project::ProjectPlugin/handleTreeRefresh()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.plugins.clean::CleanProject/onProjectFolderComplete()
:
: Click here to Report a Bug
: Project files cleaned successfully: NewRoyalConvertProject
```

**Comment by joshtynjala** [comment] 2022-07-08 16:02
@piotrzarzycki21 Oh, yes, I see. It's possible for `tmpFW.children` to be `null`. Fixed. Please try again!

**Comment by JoelProminic** [comment] 2022-07-08 23:02
I have been working on a Java Gradle project using the latest build over the last couple days, and I haven't noticed the sorting issue trigger so far.  I also couldn't reproduce the Clean Project bug.

**Comment by piotrzarzycki21** [comment] 2022-07-09 03:46
> @piotrzarzycki21 Oh, yes, I see. It's possible for `tmpFW.children` to be `null`. Fixed. Please try again!

Yep. It's fixed. Thank you! :)

**Comment by JoelProminic** [comment] 2022-07-13 17:16
I haven't seen any more issues with the sorting in the sidebar.  I'm closing this issue for now.

**Closed by JoelProminic** 2022-07-13 17:16 UTC
Labels: bug, investigation
