### ISSUE TITLE
All other background code intelligence activity should pause when an update is being applied

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#923] opened 2021-11-15 10:22 UTC
From @JustinProminic 

> I think we should adjust the startup sequence on Moonshine.
> 
> Try this:
> 
> Have a big project in Moonshine like Moonshine itself present in your left navigator.
> 
> Close Moonshine.
> 
> Update the MoonshineDevelopment build number.
> 
> Open Moonshine.
> 
> Your computer will be VERY overwhelmed if you:
> 
> a) choose to proceed with the update, so it is download the update
> b) Moonshine is in the background ALSO trying to spin-up the workspace / code intelligence / language server stuff for the big project
> 
> 
> We should NOT be doing anything along the lines of (b) until the user has decided whether to install the update or not.   If they decide to install the update, Moonshine should NOT start up the code intelligence / workspace subsystem / workers...

**Comment by JoelProminic** [comment] 2021-11-15 19:49
I think we may want to wait to open the projects at all until the user cancels the update prompt.  This will avoid unnecessary processing without changing the project opening flow.

The disadvantage of this is that the user will need to wait this full loading time to use the projects after closing the prompt.  I'm not to worried about this case, though, since we want users to upgrade at this point.

**Comment by rat-moonshine** [comment] 2021-11-17 10:49
Yeah.. it is true that user may needs to wait longer when s/he has a slow connection and the update-notification data loads. Usually, opening of projects do not waits for an update check in other IDEs. But they also don't slows-down running processes when user chose to download an update.

Perhaps, we can try the downloading in a thread and let continue the currently running processes on main.

**Comment by rat-moonshine** [comment] 2021-11-18 12:07
@JustinProminic suggested for more of a sequential approach than a thread approach.

With the implementation Moonshine suggestively to work this way:
1. Moonshine starts
2. A message/splash-popup would appear stating that update-check is in process - Moonshine will not start auto-loading any project during the visibility of this popup
3. The said popup/splash may have a cancel button - in case user do not wants to wait. If a cancellation requested, the popup will disappear and starts followed by process
4. Once update data loads from remote, it'll display for an update notification. If there's no update available, the popup will disappear and start followed by process
5. If there's an update and user chose to download/install the update, Moonshine will download the update and will not start any followed by process other than download and install
6. If user chose not to install the new update, once the update-notification cancelled Moonshine will start any followed by process

Saying 'followed by process' I meant of opening any project, files, or start any visible tasks.

If we want to halt any user interaction during the update-check and update-notification popup is visible - we may need to work on that separately. Beside disabling any click-to-action in Moonshine interface, one can also access its menu system to start an action. We may need to separately disable menu systems if we want to do it that way.

**Comment by JoelProminic** [comment] 2021-12-02 21:54
I have also noticed that any language servers that are started before Moonshine updated will not close properly.  I suspect that Moonshine is not running the full shutdown process in this case.

I also saw this problem when an update is canceled (see #951).

I think we want avoid this problem by not opening any processes or starting language servers while the update prompt is showing, as discussed above.

**Comment by rat-moonshine** [comment] 2021-12-03 12:53
I have committed an initial version of the [plan](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/923#issuecomment-972805978) we discussed. Currently, this can be tested with Moonshine Bamboo branch build plans. 

Please, check.

**Comment by JoelProminic** [comment] 2021-12-03 19:32
This seems to be working well.  I see that for the checking for updates message there is nothing in the background, but Getting Started and the console load by the time the update prompt appears:
![image](https://user-images.githubusercontent.com/24532731/144661859-c7af5f16-032c-4ceb-ab95-43055d63cdfb.png)

I think this good - the window looks strange without anything in the background, and I confirmed that this avoids the problems with starting the language servers.

We should do a test with the network disabled to make sure the prompts will handle network errors correctly.  I would expect Moonshine to report an error, and then open the project normally.

**Comment by rat-moonshine** [comment] 2021-12-06 06:26
If we feels, I can also prevent the Getting Started from opening in background during the update-notification is displaying. Console shall continue to appear as part of the main layout.

**Comment by rat-moonshine** [comment] 2021-12-06 09:17
> We should do a test with the network disabled to make sure the prompts will handle network errors correctly. I would expect Moonshine to report an error, and then open the project normally.

I have updated some error handling situation on UI. This includes network disconnect/disabled issue during update check as well. I have updated the matrix from #951 here https://github.com/Moonshine-IDE/Moonshine-IDE/issues/951#issuecomment-985371086.

**Comment by rat-moonshine** [comment] 2021-12-07 04:58
I'm moving this to v3.3.0 as this and #951 are both concentrate in same section and shares common implementations.

**Comment by JoelProminic** [comment] 2021-12-07 21:13
I tried a test on Windows with the latest branch build (264), and I found that it got stuck on this step:
![image](https://user-images.githubusercontent.com/24532731/145106751-82985385-08ae-44a9-af48-07b52c19bbad.png)

I confirmed that moonshine-ide.com is accessible in a browser on the same Windows VM.

**Comment by rat-moonshine** [comment] 2021-12-08 10:41
The above problem should have rectified now. Please, check.

**Comment by JoelProminic** [comment] 2021-12-08 17:32
I need to try an update test for Windows, but otherwise this looks good.  Go ahead and merge, and we'll finish testing this in the nightly builds.

**Comment by JoelProminic** [comment] 2021-12-08 18:04
We would like to have a Cancel (or Close) button for the "An update check is in progress" panel, so that the user can skip the update if it is unusually slow (or hangs).

**Comment by rat-moonshine** [comment] 2021-12-14 06:42
> We would like to have a Cancel (or Close) button for the "An update check is in progress" panel, so that the user can skip the update if it is unusually slow (or hangs).

A cancellation option now being added while update check is in progress. Please, check.

**Comment by rat-moonshine** [comment] 2021-12-15 17:04
Merged to `master`.

**Comment by JoelProminic** [comment] 2021-12-15 22:45
I see an "x" button was added to the "An update check is in progress" panel.  This should be fine, but I had some problems (that are difficult to screenshot) during testing.
- I tried to click the "x" button, but nothing happened.  I don't have much time to click this in my tests, so I may have been slightly too late.
- When opening Moonshine with  maximized resolution, the prompt was distorted while Moonshine tried to update the resolution, so the update prompt is barely readable.   The delayed resolution adjustment is a known issue, though, so we may not be able to to much about this without a larger update.

**Comment by JoelProminic** [comment] 2021-12-16 22:08
I was able to do a better test on macOS, and it does seem that the "x" button doesn't work there - the download prompt updates anyway.   I'd like to address this before the upcoming release - hopefully it will be an easy fix.

**Comment by rat-moonshine** [comment] 2021-12-17 06:08
Due to the quick turnover of the event I haven't noticed that it throws an exception in certain test-case. 

I fixed the exceptions and this should run smoothly now. I able to produce the error earlier by doing some changes in debug-code. I don't offer any reproducible steps however.

**Comment by JoelProminic** [comment] 2021-12-21 21:40
It still seems like the "x" button doesn't work for Moonshine, but the timing is so fast that it is hard to tell if it is actually a problem.  If you have confirmed that clicking the "x" button stops the update check, though, then that should be good enough for this release.

**Closed** 2021-12-22 17:18 UTC
Labels: enhancement, test-ready
