### ISSUE TITLE
Move "About" view to Haxe

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Moonshine-IDE#1024] opened 2022-04-13 18:02 UTC
Following view should be moved to Haxe (Rewritten component has to be placed in [MoonshineGUICore](https://github.com/Moonshine-IDE/Moonshine-IDE/tree/master/ide/MoonshineGUICore)):

<img width="1463" alt="Screenshot 2022-04-14 at 10 20 33" src="https://user-images.githubusercontent.com/24554795/163344353-4e160dad-ad88-4268-a1e6-cdf4135413d1.png">

You can reach this view by going to menu **Help** -> *About**

In Flex view is being implemented in following file
https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/components/popup/SoftwareInformationSDKs.mxml

EDIT:  Branch and build information:
Moonshine branch:  features/issue_1024_Haxe_AboutScreen
MSDKI branch:  features/haxeconversion
Bamboo build:  https://moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1024_Haxe_AboutScreen/

**Comment by piotrzarzycki21** [comment] 2022-04-14 08:23
@rat-moonshine correct me if I'm pointing to the wrong file in Flex.

**Comment by piotrzarzycki21** [comment] 2022-04-14 08:30
@Igazine In order to get on board with developing you need to setup Moonshine sources. I'm personally using Intellij IDEA for Moonshine development and Moonshine IDE itself to develop [MoonshineGUICore](https://github.com/Moonshine-IDE/Moonshine-IDE/tree/master/ide/MoonshineGUICore) - In the other words when I do changes in that library I'm building it using ANT and later I run Moonshine build with fresh version of library from Intellij. 

I think you can also setup Moonshine source code in VSCode, but I didn't do that yet. If you decide to use Intellij let me know we can have quick session to guide you trough that.

**Comment by Igazine** [comment] 2022-04-14 08:33
I have everything checked out form the repo (and the other ones as well), I'll make the necessary SWCs based on Haxe code that can be imported in the current logic replacing the ActionScript code.

Thank you

**Comment by piotrzarzycki21** [comment] 2022-04-14 08:46
please any changes do on a branch usually we are using convention to create branches:

features/issue_number_some_info
bugfix/issue_number_some_info

**Comment by rat-moonshine** [comment] 2022-04-14 09:36
> @rat-moonshine correct me if I'm pointing to the wrong file in Flex.

https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/help/view/AboutScreen.mxml is the file that showing up in a tab on `Help > About`.

**Comment by piotrzarzycki21** [comment] 2022-06-09 06:46
@Igazine This is the issue which you should use if you reached to migrate that part. Create branch out of master, merge everything what you did from migration branch and start working. Let me know when you do that I would like to follow.

**Comment by Igazine** [comment] 2022-06-22 15:00
https://github.com/Moonshine-IDE/Moonshine-IDE/tree/features/issue_1024_Haxe_AboutScreen

AboutScreen is working, it can be tested, the code can be examined. The SWC is also updated and committed.

Still needed to do:
* Some styling still needed to be done on the scroll bar
* I have to disable the interaction of the itemrenderers until all the data is loaded
* Some data binding is lost (elsewhere in the app, related to converted components)

**Comment by Igazine** [comment] 2022-06-22 15:02
Rebuild the SWC separately with `ant CompileGUICore` command. Use `ant CompileGUICore -Dnohaxelib=1` if you want to skip the Haxelib check for consequent builds (can be annoyingly long after a while)

**Comment by Igazine** [comment] 2022-06-22 15:15
Update: please pull the changes from https://github.com/Moonshine-IDE/Moonshine-SDK-Installer repo as well, as the code base is shared between these repos and changes have been made in that as well

**Comment by rat-moonshine** [comment] 2022-06-24 06:13
@Igazine If you make changes to any interface classes, i.e. `IContextMenuBridge`, please make sure corresponding declaration is available in Web Moonshine implementation - https://github.com/Moonshine-IDE/Moonshine-IDE/tree/master/ide/MoonshineWEBevolved/src/actionScripts/impls, it is alright if you just placed a blank method to overcome any such compilation error.

**Comment by Igazine** [comment] 2022-06-24 06:24
Looks like this WEBevovled has the same classes (duplicate files) instead of using a common code base, so I have to go through this part as well and get rid of old AS files, forcing it to use the definitions in the SWC instead. I did not change anything in the signature, it's natural signatures get messed up if the same classes exist in the SWC and in the source path as well

**Comment by JoelProminic** [comment] 2022-06-24 17:36
To give some context, MoonshineWEBevolved was intended to run in a web browser and interact with a remote filesystem through alternative implementations of the `I...Bridge` interfaces.  At some point we moved away from this idea, so I think we have just been adding placeholder classes in MoonshineWEBevolved to resolve the build errors.

I'm a little concerned about the "get rid of old AS files, forcing it to use the definitions in the SWC instead" plan.  Are we undoing some design work for keeping the logic distinct in this case?   On the other hand, if the classes didn't need to be different in the first place, then the classes should have been in MoonshineSharedCore anyway.

@Igazine, How much extra work will it be to handle the Haxe conversion with the separate WEB/DESKTOP design.  If it is going to be a lot of work, we may want to reconsider whether we should keep "maintaining" MoonshineWEBevolved.

**Comment by Igazine** [comment] 2022-06-24 18:01
> How much extra work will it be to handle the Haxe conversion with the separate WEB/DESKTOP design. If it is going to be a lot of work, we may want to reconsider whether we should keep "maintaining" MoonshineWEBevolved.

I wasn't sure what's the role of the WEBevolved part, I always assumed it's a Flash based sort-of-limited and kind-of-obsolete version of Moonshine. If it's needed, it can be kept alive as long as the SWF target is maintained by Haxe and only the Flash API is being used in the code.

According to [Haxe website](https://haxe.org/documentation/introduction/compiler-targets.html) the SWF target is in Tier 3 which is a _"kept up-to-date, but not much active development"_ tier.

**Comment by Igazine** [comment] 2022-06-24 18:32
Changes/fixes have been committed, WEBevolved is compiling fine now on my environment

**Comment by JoelProminic** [comment] 2022-06-24 19:19
@Igazine, great, I just wanted to make sure we were all on the same page.   Yeah, I think we moved away from the Web version once it became clear that modern web browsers weren't going to support Flash anymore.  I don't want to spend too much time on this for now.

I confirmed the Bamboo build was successful, and I see the installers [here](https://moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_1024_Haxe_AboutScreen/).  Let me know when the next Bamboo branch is ready for testing, and I can update Bamboo to build that.  This could be more automated, but I don't want to spend too much time on Bamboo when we want to be moving towards GitHub Actions.  Right now I only have a macOS build, but I should setup a Windows build as well.

I did some tests with the new build on macOS:

![image](https://user-images.githubusercontent.com/24532731/175650916-5ee13d66-37cd-44b3-9a03-be6f1529a2c5.png)


Test | Result
-----|------
Open About Page | This works, though it is a bit strange that the entire scrollable panel is greyed out until all the versions are populated.
Version populate | The versions are populated, and I don't see a problem
Tabs | Switching works properly
"About the background image" | Works
Copy to Clipboard | Works

**Comment by Igazine** [comment] 2022-06-24 19:25
Thank you for testing.

The reason it's being populated at once (so with some delay) is because in Flex those cells are data bound, so whenever a single sub-component is updated with values, the result is shown/updated.

In Haxe/OpenFL/Feathers there's no equivalent of data binding, so the cells get updated when every sub-component is updated. I implemented the disabled list to make sure users don't get confused.

I can certainly implement an update event logic for every sub-component, it's not a significant task.

**Comment by Igazine** [comment] 2022-06-24 19:30
Further minor issues:

* The border of the list doesn't exactly look like in the Flex version, it's because of the different implementation of Feathers' TabNavigator and its styling
* The progress indicator (at top right, which is later replaced by the copy to clipboard button) is a pure Flex component, which cannot be directly converted. I'll figure out a quick solution for a Feathers progress indicator that can be used elsewhere in the software

**Comment by rat-moonshine** [comment] 2022-06-27 04:56
On comments from @Igazine ,

> I wasn't sure what's the role of the WEBevolved part, I always assumed it's a Flash based sort-of-limited and kind-of-obsolete version of Moonshine. If it's needed, it can be kept alive as long as the SWF target is maintained by Haxe and only the Flash API is being used in the code.

As @JoelProminic pointed we started to support Moonshine in dual platforms - desktop and web. Thus, we chose to share non-factory classes between the projects through interfaces, i.e. `IContextMenuBridgeImp` or many others.

We do not updates web version of Moonshine anymore. Since it is still there, and we time to time adds/updates in the interface classes resides in MoonshineSharedCore, we also needs to update the method stamp in web Moonshine's classes that implements these interfaces. Since we're not expecting any valid outcome from those methods in web Moonshine, we just left the method declarations blank. This will prevent us from any compilation error as you've pointed.

At a time we surely get rid of this web codebase, currently we're still connected with these legacy codes.

**Comment by rat-moonshine** [comment] 2022-06-27 05:10
From @Igazine 

> Still needed to do:
> I have to disable the interaction of the itemrenderers until all the data is loaded

Can you please elaborate why do we need to have the list disabled until its complete data loads?

If I toggle between "Configured SDKs" and "External Editors", then I can see partial data being loaded into "Configured SDKs" list. It seems like partially data does injecting to the interface, then we would want to disable the list at first place (?)

From a user point this confuse me. I started thinking why it's disabled and there wasn't any message to wait either.

**Comment by rat-moonshine** [comment] 2022-06-27 05:14
![image](https://user-images.githubusercontent.com/24370870/175864700-4d9738d2-a67a-4264-afaf-afd9f00eca64.png)

Seeing into the converted interface, I think we can remove this horizontal line between Moonshine and software version details, unless we have some hidden messages placed beneath the line.

**Comment by piotrzarzycki21** [comment] 2022-10-27 08:16
@Igazine this is exception when I enter About screen in Moonshine 3.3.4 build: 2851:

```
: Error #1069
: ReferenceError: Error #1069
: 	at moonshine.plugin.help.view.about::AboutScreen/getSDKs()
: 	at moonshine.plugin.help.view.about::AboutScreen/layoutGroup_addedToStageHandler()
: 	at mx.core::UIComponent/http://www.adobe.com/2006/flex/mx/internal::$addChildAt()
: 	at mx.core::Container/addChildAt()
: 	at mx.core::Container/addChild()
: 	at actionScripts.ui.tabview::TabView/addChild()
: 	at actionScripts.ui::MainView/handleEditorChange()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.collections::ListCollectionView/dispatchEvent()
: 	at mx.collections::ListCollectionView/addItemsToView()
: 	at mx.collections::ListCollectionView/listChangeHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.collections::ArrayList/internalDispatchEvent()
: 	at mx.collections::ArrayList/addItemAt()
: 	at mx.collections::ListCollectionView/addItemAt()
: 	at mx.collections::ListCollectionView/addItem()
: 	at actionScripts.controllers::AddTabCommand/execute()
: 	at actionScripts.locator::IDEController/execCommand()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.plugin.help::HelpPlugin/abouthShowHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.utils::KeyboardShortcutManager/dispatch()
: 	at actionScripts.utils::KeyboardShortcutManager/stopEvent()
: 	at actionScripts.ui.menu::MenuPlugin/redispatch()
: 	at Function/<anonymous>()
: 	at actionScripts.impls::INativeMenuItemBridgeImp/_trigger()
```

Fix this as part of this issue.

**Comment by JoelProminic** [comment] 2022-11-02 17:49
I see a slightly different error in my tests today:

    : Error #1069
    : ReferenceError: Error #1069
    : 	at moonshine.plugin.help.view.about::AboutScreen/getSDKs()
    : 	at moonshine.plugin.help.view.about::AboutScreen/initialize()
    : 	at feathers.core::FeathersControl/initializeNow()
    : 	at actionScripts.ui::FeathersUIWrapper/set feathersUIControl()
    : 	at actionScripts.ui::FeathersUIWrapper()
    : 	at actionScripts.ui.feathersWrapper.help::AboutScreenWrapper()
    : 	at actionScripts.impls::IAboutBridgeImp/getNewAbout()
    : 	at actionScripts.plugin.help::HelpPlugin/abouthShowHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.utils::KeyboardShortcutManager/dispatch()
    : 	at actionScripts.utils::KeyboardShortcutManager/stopEvent()
    : 	at actionScripts.ui.menu::MenuPlugin/redispatch()
    : 	at Function/<anonymous>()
    : 	at actionScripts.impls::INativeMenuItemBridgeImp/_trigger()
    :
    : Click here to Report a Bug

**Comment by JoelProminic** [comment] 2022-11-10 23:08
Help > About works properly for me on macOS now.

However, I see that Moonshine > About does not work - nothing triggers when I try this action.  I confirmed this was working in Moonshine 3.3.3, so I think this is related to the Haxe conversion

**Comment by Igazine** [comment] 2022-11-14 13:43
The About menu issue is related to #1115 which is now fixed

**Comment by JoelProminic** [comment] 2022-11-14 16:01
I confirmed that both Help > About and Moonshine > About work now on macOS.  Are there any other updates pending for this issue?

**Comment by Igazine** [comment] 2022-11-14 16:02
@JoelProminic nope, this and the related issue can be closed or marked as fixed. thank you

**Comment by piotrzarzycki21** [comment] 2022-11-15 09:50
Please close the issue.

**Closed** 2022-11-15 09:52 UTC
Labels: enhancement, haxe migration
