### ISSUE TITLE
Moonshine to Run On System Default Font

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#873] opened 2021-07-01 07:46 UTC
We were discussing on removing the embedded font dependency in Moonshine (DejaVu) and moved to run on system's default font.

We also noticed different problems with font-face when using the embedded font through Haxe UI, when using no embedded-font looks much prominent and clear.

**Comment by rat-moonshine** [comment] 2021-07-01 07:48
Submitted first version of Haxe libraries replacing the embedded fonts with system's default font. I can say the texts are looking much more solid and clear.

**Comment by JoelProminic** [comment] 2021-07-07 17:04
I'd like to do some tests with changing the system font here, to see if this will update Moonshine as expected (and if it will cause trouble).

Santanu reported that on Windows it is hard-coded to use the same font that Windows uses as the default, so it won't update if we change the default system font.

**Comment by JoelProminic** [comment] 2021-07-14 16:53
On Windows, we noticed that the text editor no longer uses fixed-width font.  We need to fix this at least before the release:

![image](https://user-images.githubusercontent.com/24532731/125661626-122b3439-20d3-4d9b-b0ae-d36bcc66c8bd.png)

**Comment by rat-moonshine** [comment] 2021-07-16 07:29
Good news! With newer SDK downloaded through MSDKI using changes(https://github.com/Moonshine-IDE/Moonshine-SDK-Installer/issues/32), the font issue is gone on Windows. 

I have installed the newer SDK on Windows currently, I'll going to do that same on macOS - to see if the remaining issue(https://github.com/Moonshine-IDE/Moonshine-SDK-Installer/issues/59) could resolved.

**Comment by piotrzarzycki21** [comment] 2021-07-16 10:45
Downloading nightly I'm getting following when I try to run Moonshine. 
<img width="408" alt="Screenshot 2021-07-16 at 12 44 27" src="https://user-images.githubusercontent.com/24554795/125936181-b4e223d7-a31a-4f70-9833-8e4679a62264.png">

**Comment by piotrzarzycki21** [comment] 2021-07-16 10:48
SDK Installer latest nightly working

**Comment by JoelProminic** [comment] 2021-07-21 16:48
The "This application requires a version of Adobe AIR which cannot be found" error was caused by missing symlinks in the SDK.   See the notes here:
https://github.com/Moonshine-IDE/Moonshine-SDK-Installer/issues/32#issuecomment-883512757

**Comment by JoelProminic** [comment] 2021-07-21 16:49
I confirmed that the Windows Editor font is fixed now.

The font was only updated on the Haxe side.  We will continue working on  the font update on the Flex side in the next milestone.

**Comment by rat-moonshine** [comment] 2021-11-12 11:51
I have updated rest of the areas to use system-font across Windows and macOS. Let me know if you see broken font anywhere, or font too small to read in any important place.

Editors continue to use the same embedded font (https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/valueObjects/FontSettings.as). I don't have any better idea what alternative font we could have here (@joshtynjala ). This can port as it is, for now.

Please, give some tests and report for any break.

**Comment by joshtynjala** [comment] 2021-11-12 17:37
In Flash/AIR, `_typewriter` a generic monospaced font, similar to how `_sans` is a generic sans-serif font.

**Comment by rat-moonshine** [comment] 2021-11-15 07:26
I think we're using that in console too. Looking into the fairness of the font, I'd like to keep the current embedded font to use in editors. I feel it'd be better looking than writing the codes in courrier-type font.

**Closed** 2021-11-18 09:21 UTC
Labels: enhancement, test-ready

**Comment by piotrzarzycki21** [comment] 2022-01-20 11:11
@rat-moonshine If we are using system default font - do we still need in [style.css](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/4014a7c6e5b270218091a13d9a141dba1b4b61d8/ide/MoonshineSharedCore/src/elements/style/style.css#L10) any of this paths to font files ? Can we remove them along with files ?

**Comment by rat-moonshine** [comment] 2022-01-20 11:18
No. As I've mentioned [earlier](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/873#issuecomment-967042429), the editor is still using the embedded font. My reasoning to keep the using for for [this](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/873#issuecomment-968606396). We shall keep having the embedded fonts for some time, I guess.
