### ISSUE TITLE
New Royale Project Initiation Is Not Correct

### ISSUE THREAD

**Issue by Bilbosax** [Moonshine-IDE/Moonshine-IDE#778] opened 2021-01-28 16:27 UTC
I just downloaded Moonshine, installed Flex, Royale 0.9.8 nightly build, and tried to start a new Apache Royale Browser application.  As you can see from these screenshots, the initiated main application mxml file, and the MainContent.mxml files both look like they do not have access to some of the classes that are necessary to make the app function.  Have I failed to install something or set something up properly, because j:ApplicationResponsiveView does not seem to be recognized?? Thanks

![Screenshot (64)](https://user-images.githubusercontent.com/23325601/106167909-b3b78880-615b-11eb-865c-cee50d2fcb99.png)
![Screenshot (65)](https://user-images.githubusercontent.com/23325601/106167921-b7e3a600-615b-11eb-9f02-ce5697e6f29a.png)

**Comment by piotrzarzycki21** [comment] 2021-01-28 16:38
Thanks for raising that issue. Yes we know about that. It will be fixed once Royale 0.9.8 gets release. Please adjust that to ResponsiveView.

**Comment by Bilbosax** [comment] 2021-01-28 23:21
I am not an ace programmer like most here so I could be way off here, but I think your problem may be more than just adjusting to "ResponsiveView".  Even if I do that, which helps, the initialView tag is still not recognized.  I was trying out VS Code but pointing to Moonshines versions of the Royale SDK, and it did not recognize the initialView tag either, but when I switched to using the SDK downloaded by npm, it works just fine.

I'm concerned with the SDK's that your app is downloading and installing.  Could there be a problem there??

**Comment by piotrzarzycki21** [comment] 2021-01-29 05:06
I need to adjust internal template in Moonshine once Royale got release, so this issue should stay open. 

If you have any problems with Moonshine, first thing which you should try is download Nightly build, which contains lot's of improvements.

**Comment by JoelProminic** [comment] 2021-10-01 14:48
I confirmed that the Royale Jewel template works without modification for the 0.9.9 SDK.   It is probably worth doing test with Royale Basic, Windows, and the 0.9.8 SDK, but this looks promising so far.

**Comment by JoelProminic** [comment] 2021-10-05 17:38
I did more testing with the latest nightly builds, and this seems to be working well:
OS | Project Type | SDK | Result
---|--------------|-----|-------
macOS | Jewel | 0.9.9 | Works
macOS | Jewel | 0.9.8 | Works
macOS | Basic | 0.9.9 | Works
macOS | Basic | 0.9.8 | Works
Windows | Jewel | 0.9.9 | Works
Windows | Jewel | 0.9.8 | Works
Windows | Basic | 0.9.9 | Works
Windows | Basic | 0.9.8 | Works

**Closed by JoelProminic** 2021-10-05 17:38 UTC
Labels: bug
