### ISSUE TITLE
Getting Started Does Not Open Automatically

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#844] opened 2021-06-10 20:06 UTC
I have noticed that the Getting Started page doesn't open automatically then there are missing SDKs currently.  I'm testing on macOS Mojave with the Moonshine 3.1.1 release:
1. Open Help > Getting Started, and ensure that the "Do not show this tab on startup" option is *not* enabled.
1. Close all open projects and tabs in Moonshine
1. Close Moonshine
1. Rename ~/Downloads/Moonshine SDKs so that the SDKs will not be found
1. Start Moonshine
1. BUG:  The Getting Started page does not open.  It does show a warning for the default SDK
1. Manually setup a default Flex SDK in Settings > Default SDK
1. Restart Moonshine
1. BUG:  The Getting Started page does not open.  It does show a warning for the default SDK

![image](https://user-images.githubusercontent.com/24532731/121590132-8f1ec780-c9fd-11eb-9ae7-8a7215c0e7d5.png)

If this is broken for all users, then we may want to consider another quick release.  This step is important for the intial setup process of Moonshine.  Otherwise the users have to know to open Help > Getting Started or manually download the Moonshine SDK Installer.

**Comment by rat-moonshine** [comment] 2021-06-11 16:04
In my quick tests I couldn't able to reproduce the problems described in 1-6.

I was using El Capitan, and Getting Started opened for me each time correctly. 

@Aszusz , @piotrzarzycki21 do you also see the same problem as @JoelProminic reported (?) I'm wondering if I'm missing some test-areas or not.

**Comment by JoelProminic** [comment] 2021-06-11 16:20
I sent those by email.  The correct path is `~/Library/Application Support/com.moonshine-ide/Local Store/#SharedObjects/bin-debug/Moonshine.swf`

**Comment by rat-moonshine** [comment] 2021-06-14 04:58
Replacing all the cookie files (at me) with @JoelProminic 's, I couldn't able to reproduce the problem as reported per the steps. That points me this might not a problem with the cookies (he's using) however the opening of Getting Started window depends upon the cookie data. 

I don't have a clear understanding yet as I couldn't able to reproduce it.

**Comment by JoelProminic** [comment] 2021-06-14 14:37
If I rename `~/Library/Application Support/com.moonshine-ide` to reset the settings, I see the Getting Started page again.  If I then put the original `~/Library/Application Support/com.moonshine-ide` directory back, I find that Getting Started now opens again!  Do you have any ideas about what could cause this behavior?

**Comment by piotrzarzycki21** [comment] 2021-06-22 15:04
I have tested this on Catalina and Big Sur - To me even  without original scenario Getting Started do not show up when I'm launching Moonshine. @rat-moonshine If you cannot reporduce that issue maybe I will be able to in debug mode from IDE.

**Comment by rat-moonshine** [comment] 2021-06-22 15:42
Hopefully you ensured that "Do not show show this tab on startup" option is unchecked for you. Yes, please go ahead to do a debug and if you can trace where it's failing.

**Comment by piotrzarzycki21** [comment] 2021-06-23 11:44
I'm not sure how it has to work. In cookie property responsible for showing Getting Started on my end is not present at all -> isGettingStartedDNS.
There is also no place where this property is set to `true` in scenario when user installing Moonshine for the first time on their system. How is it actually working ?

**Comment by piotrzarzycki21** [comment] 2021-06-23 12:09
Actually this property should be false and it seems to have correct value, so ignore my last comment.

**Comment by piotrzarzycki21** [comment] 2021-06-23 15:42
Can someone take a look into bamboo @rat-moonshine , @JoelProminic - It looks like my changes are not being picked up.

**Comment by JoelProminic** [comment] 2021-06-23 21:21
Bamboo is working again now. 

I tested the latest build on macOS 10.13.6, but I see that the Getting Started page still doesn't load automatically.  I haven't touched the "Do not show this tab on startup" checkbox on this machine (as far as I can remember), so I can use it to help test this bug.

**Comment by rat-moonshine** [comment] 2021-07-06 17:22
I able to reproduce this problem myself after being updated to build.2024. I'm wondering what could be the difference in this latest build from the earlier. Anyway, I'll check.

**Comment by rat-moonshine** [comment] 2021-07-07 09:26
I commit a fix. Should help on opening the Getting Started effectively, @JoelProminic please test on `master`.

**Comment by JoelProminic** [comment] 2021-07-07 16:57
By my understanding, this was triggering when there was only one SDK that was not configured.  I did some tests on macOS, and I wasn't able to reproduce the bug.  I'd like to do a quick test on Windows, and then we can close this issue.

**Comment by piotrzarzycki21** [comment] 2021-07-14 10:01
@Aszusz please test this on Windows - download newest nightly build. Let's close it.

**Comment by Aszusz** [comment] 2021-07-14 11:46
I tested this on Windows and it seems to be working correctly:
- if any of the SDKs is missing Getting Started appears
- when I check "Do not show show this tab on startup" it stops Getting Started from appearing
- when I uncheck it, it starts appearing again
- if the default SDK is not set I get the "some options may be unavailable"

In my opinion we can close this issue.

**Closed** 2021-07-14 12:11 UTC
Labels: CRITICAL, bug, test-ready
